#!/usr/bin/env python
# Copyright (C) 2011 Midokura KK
#
# Midolman Net Agent service
import cmd
import os
import sys

from optparse import OptionParser

# If ../midolman/src/midolman/__init__.py exists, add ../ to Python search
# path, so that it will override what happens to be installed in
# /usr/(local/)lib/python...
possible_topdir = os.path.normpath(os.path.join(os.path.abspath(sys.argv[0]),
                                   os.pardir,
                                   os.pardir))
if os.path.exists(os.path.join(possible_topdir, 'src/midolman',
                               '__init__.py')):
    sys.path.insert(0, "%s/src" % possible_topdir)

from midolman.agent.config import Config
from midolman.agent.server import NetAgentTCPServer

def parse_options():
    """Parses the options from sys.argv.  Returns a tuple of options and args.
    """
    # Initialize the parser
    usage = "usage: %prog [options]"
    parser = OptionParser(usage=usage)
    parser.add_option("-c", "--conf", action="store", type="string",
                      dest="conf", default="/etc/midolman-agent.conf",
                      help="configuration file for the service")

    # Parse the options
    return parser.parse_args()

def main(argv=None):
    """Main entry for Midolman Net Agent service
    """
    # Parse options
    options, _args = parse_options()

    # Initialize config
    Config.read(options.conf)

    # Run the server
    server = NetAgentTCPServer((Config.server_host, Config.server_port))
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        sys.exit(0)

if __name__ == '__main__':
    sys.exit(main())

